Some Improvement in aspect processing
i4Ds/STIX-GSW pull request #179
Opened 2023-09-19 13:31 UTC by FredSchuller

Updates in several procedures called to process SAS data, including:
- added a procedure stx_remove_bad_sas_data
- updates in SAS_test to call procedures with name stx_...
- store error codes in data.ERROR (partly addresses issue #129). So far only these codes are implemented:
  - SUN_TOO_FAR (when distance > 0.75 AU)
  - NO_ASPECT_SOL (if for some reason the computation resulted in NaN)
  - SAS_DATA_WRONG_DURATION (for HK data where deviation deviates from the expected 64s, e.g. for duplicated entries)

2023-10-10 14:49 UTC, samaloney commented
Since we will fix the HK data maybe the `SAS_DATA_WRONG_DURATION` isn't needed? Also all the status message seem different if I'd suggest either in clue `SAS_` in all or remove from all 

| Current | Sun |
|--------|--------|
| SUN_TOO_FAR | SUN_TOO_SMALL / SUN_TOO_FAR |
| SUN_TOO_BIG | SUN_TOO_BIG / SUN_TOO_CLOSE |
| SAS_SOL_TOO_FAR | OFFPOINT_TOO_LARGE |
| NO_ASPECT_SOL | NO_SOLUTION | 

Also not sure how the plan to encode but a number would be better 0, 1, 2, 3 can be stores as two bits

2023-10-11 13:39 UTC, FredSchuller commented
I'm happy to rename the error messages as you suggest. Still, I would keep the possibility for WRONG_DURATION (we can use a shorter text if you prefer) as long as the issue is not fixed - and it may happen again in the future...

The plan is to include this error message AND a boolean (or short integer) "SAS_OK" in the AUX fits file. The imaging pipeline will only make use of the later, to filter out every SAS measurement that is not OK, for any reason.

2023-10-13 10:00 UTC, FredSchuller commented
@samaloney
I have updated the error messages as per your suggestion. From my point of view, this PR could be merged now.

2023-10-18 10:38 UTC, samaloney commented
Yea looks good to me but I'd like to get @nicHoch input. In particular I'm not sure including both the string and error code/boolean make sense not in the fits file itself  anyway.

2023-10-24 08:12 UTC, nicHoch commented
it was planed as String in order to provide the user with a verbose error reason. most of the time the string will be empty. but we could also change it to ENUM and add the verbose messages to the column description

2023-10-27 14:26 UTC, nicHoch requested changes
the order is important in idl struct definition so it should be exactly like this:

** Structure STX_ASPECT_DTO, 16 tags, length=144, data length=134:
   CHA_DIODE0      DOUBLE           1.3056000
   CHA_DIODE1      DOUBLE           1.0624000
   CHB_DIODE0      DOUBLE          0.99840000
   CHB_DIODE1      DOUBLE           1.0256000
   TIME            STRING    '2022-05-09T23:59:03.379947'
   SCET_TIME_C     LONG64                 705455824
   SCET_TIME_F     LONG64                     31305
   DURATION        DOUBLE           64.000000
   SPICE_DISC_SIZE DOUBLE           1233.2347
   Y_SRF           DOUBLE           0.0000000
   Z_SRF           DOUBLE           0.0000000
   CALIB           DOUBLE           0.0000000
   SAS_OK          INT              0
   ERROR           STRING    ''
   CONTROL_INDEX   LONG64                      1349
   PARENTFITS      LONG                 0

2023-10-27 14:26 UTC, nicHoch commented on stix/idl/processing/aspect/stx_smooth_sas_data.pro
> +         control_index: new_control[i], parentfits: new_parentfits[i]}
```suggestion
    a = {stx_aspect_dto, $
         cha_diode0: new_sigA[i],$
         cha_diode1: new_sigB[i],$
         chb_diode0: new_sigC[i],$
         chb_diode1: new_sigD[i],$
         time: new_utc[i],$
         scet_time_c: new_scet_c[i],$
         scet_time_f: new_scet_f[i],$
         duration: new_dura[i],$
         spice_disc_size: new_rsol[i], $
         y_srf: new_y[i],$
         z_srf: new_z[i],$
         calib: new_cal[i],$
         sas_ok: new_sas_ok[i],$
         error: new_err[i], $
         control_index: new_control[i],$
         parentfits: new_parentfits[i]}
```

2023-10-27 14:26 UTC, nicHoch commented on stix/idl/processing/aspect/stx_remove_bad_sas_data.pro
> +                control_index: data[good[i]].control_index, parentfits: data[good[i]].parentfits}
```suggestion
    one_data = {stx_aspect_dto, $
                cha_diode0: data[good[i]].cha_diode0, cha_diode1: data[good[i]].cha_diode1, $
                chb_diode0: data[good[i]].chb_diode0, chb_diode1: data[good[i]].chb_diode1, $
                time: data[good[i]].time, $
                scet_time_c: data[good[i]].scet_time_c, scet_time_f: data[good[i]].scet_time_f, $
                duration: data[good[i]].duration, $
                spice_disc_size: data[good[i]].spice_disc_size, $
                y_srf: data[good[i]].y_srf, z_srf: data[good[i]].z_srf, $
                calib: data[good[i]].calib, sas_ok : 1, error : "", $
                control_index: data[good[i]].control_index, parentfits: data[good[i]].parentfits}
```

2023-10-27 14:26 UTC, nicHoch commented on stix/idl/processing/aspect/prepare_aspect_data.pro
> +          control_index: 0L, parentfits: 0L}
```suggestion
          time: utc_str[i], $
           scet_time_c: 0LL, scet_time_f: 0LL, $
          duration : duration[i], spice_disc_size : r_sol[i], $
          y_srf : 0.0, z_srf : 0.0, calib : 0.0,  sas_ok : 1, error : "", $
          control_index: 0LL, parentfits: 0LL}
```

2023-10-31 09:59 UTC, samaloney approved these changes

2023-11-02 09:29 UTC, merged